// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:df090750-df14-432e-87a5-4718ed61c934",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_1rHhG9ZWL",
    "aws_user_pools_web_client_id": "79uaaln3d2hkifm7qso2kk7kjt",
    "oauth": {}
};


export default awsmobile;
